name: 'build'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-alpine:
    runs-on: ubuntu-latest
    container: jonlauridsen/node-nexe:10-alpine
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: EXPECTED_FILENAME=fpie2-alpine EXPECTED_OS=Alpine NEXE_TEMP=/opt/.nexe NEXE_BUILD=true npm test
      - run: NEXE_TEMP=/opt/.nexe npm run compile:build -- --output dist/fpie2-alpine
      - uses: actions/upload-artifact@master
        with:
          name: fpie2-alpine
          path: dist/fpie2-alpine
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10'
      - run: npm ci
      - run: EXPECTED_FILENAME=fpie2-macos EXPECTED_OS=Mac npm test
      - run: npm run compile -- --output dist/fpie2-macos
      - uses: actions/upload-artifact@master
        with:
          name: fpie2-macos
          path: dist/fpie2-macos
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10'
      - run: npm ci
      - run: EXPECTED_FILENAME=fpie2-ubuntu EXPECTED_OS=Ubuntu npm test
      - run: npm run compile -- --output dist/fpie2-ubuntu
      - uses: actions/upload-artifact@master
        with:
          name: fpie2-ubuntu
          path: dist/fpie2-ubuntu
