name: 'release'

on:
  release:
    types: [created]

jobs:
  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10'
      - run: npm ci
      - run: npm test
      - run: npm run compile -- --output dist/fpie2-macos
      - uses: actions/upload-artifact@master
        with:
          name: fpie2-macos
          path: dist/fpie2-macos
  release-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10'
      - run: npm ci
      - run: npm test
      - run: npm run compile -- --output dist/fpie2-ubuntu
      - uses: actions/upload-artifact@master
        with:
          name: fpie2-ubuntu
          path: dist/fpie2-ubuntu
  upload:
    runs-on: ubuntu-latest
    needs:
      - release-macos
      - release-ubuntu
    steps:
      - uses: actions/download-artifact@master
        with:
          name: fpie2-macos
          path: .
      - uses: actions/download-artifact@master
        with:
          name: fpie2-ubuntu
          path: .
      - run: ls
      - uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*'
